export const tagsOptions: readonly Option[] = [
  { value: "BOY", label: "Boy" },
  { value: "FAMILY", label: "Family" },
  { value: "FOOD", label: "Food" },
  { value: "ELECTRONICS", label: "Electronics" },
  { value: "KID", label: "Kid" },
  { value: "FASHION", label: "Fashion" },
  { value: "BEAUTY", label: "Beauty" },
  { value: "HOME", label: "Home" },
  { value: "APPLIANCES", label: "Appliances" },
  { value: "ACCESSORIES", label: "Accessories" },
  { value: "GIRL", label: "Girl" },
  { value: "TOYS", label: "Toys" },
  { value: "SPORTS", label: "Sports" },
  { value: "OUTDOORS", label: "Outdoors" },
  { value: "HEALTH", label: "Health" },
  { value: "OFFICE", label: "Office" },
  { value: "TELEVISION", label: "Television" },
  { value: "PET", label: "Pet" },
  { value: "Vehicle", label: "Vehicle" },
  { value: "GROCERY", label: "Grocery" },
  { value: "JEWELRY", label: "Jewelry" },
  { value: "SHOES", label: "Shoes" },
  { value: "WATCHES", label: "Watches" },
  { value: "FURNITURE", label: "Furniture" },
  { value: "TOOLS", label: "Tools" },
  { value: "CLOTHING", label: "Clothing" },
  { value: "AUTOMOTIVE", label: "Automotive" },
  { value: "MUSIC", label: "Music" },
  { value: "GAMES", label: "Games" },
  { value: "CAMERAS", label: "Cameras" },
  { value: "LAPTOPS", label: "Laptops" },
  { value: "SMARTPHONES", label: "Smartphones" },
  { value: "HOME_DECOR", label: "Home Decor" },
  { value: "TABLETS", label: "Tablets" },
  { value: "SALE", label: "Sale" },
  { value: "NEW_ARRIVALS", label: "New Arrivals" },
  { value: "TRENDING", label: "Trending" },
  { value: "GIFT", label: "Gift" },
  { value: "WELLNESS", label: "Wellness" },
  { value: "SEASONAL", label: "Seasonal" },
];
