import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import HeaderClient from "@/components/Header/HeaderClient";
import FooterClient from "@/components/Footer/FooterClient";
import StoreProvider from "@/contexts/StoreProvider";
import NavbarClient from "@/components/Navbar/NavbarClient";

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <HeaderClient />
          <NavbarClient />
          {children}
          <FooterClient />
        </StoreProvider>
      </body>
    </html>
  );
}
